server:
  port: 10402
  tomcat:
    max-threads: 3000
spring:
  thymeleaf:
      cache: false
  application:
    name: servicetcd1
#  datasource:
#     driver-class-name: com.mysql.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/card
#     username: root
#     password: root
#     testOnBorrow: true
#     validationQuery: SELECT 1
#     idle-timeout: 1000
#     max-idle: 200
  datasource:
      name: test
#      url: jdbc:mysql://120.77.224.50:3306/dw_01_activity
      url: jdbc:mysql://127.0.0.1:3306/dw_01_activity
      username: biuser
      password: i0Gkah5;uG
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.model
# 打印sql  
logging:  
  level:   
    com.yinian.alysis.model.mapper: DEBUG  
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  由于可能存在表字段非标准命名 不建议使用spring data jpa
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#      database: mysql
#      properties:
#        hibernate:
#          current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      maxFileSize: 20Mb
      maxRequestSize: 20Mb